# Use Open AI with key
provider: autogen_ext.models.openai.OpenAIChatCompletionClient
config:
  model: deepseek-chat
  api_key: sk-762dd4e1ff484f7bb06ef80e9b08d27d
  base_url: https://api.deepseek.com
  model_info:
    vision: false
    function_calling: true
    json_output: true
    family: unknown
    structured_output: true